#!/usr/bin/env bash
set -euo pipefail

# Everything downloaded or generated by this script stays outside the code repo.
llama_commit=81bc6b83f827df746eb129235488d325c49cae52
model_sha256=fb044e93939a70469c905781334f5de1e6c8b608ced6cbc8c9249bd4127d9526
llama_dir=${LLAMA_CPP_DIR:-"$HOME/llama.cpp"}
model_dir=${MODEL_DIR:-"$HOME/models"}
model_path="$model_dir/Qwen3.5-0.8B-Q4_K_M.gguf"
model_url=https://huggingface.co/bartowski/Qwen_Qwen3.5-0.8B-GGUF/resolve/main/Qwen_Qwen3.5-0.8B-Q4_K_M.gguf

if ! command -v cmake >/dev/null || ! command -v c++ >/dev/null || ! command -v git >/dev/null || ! command -v curl >/dev/null; then
  sudo apt-get update
  sudo apt-get install -y cmake build-essential git curl
fi

if [[ ! -d "$llama_dir/.git" ]]; then
  mkdir -p "$llama_dir"
  git -C "$llama_dir" init
  git -C "$llama_dir" remote add origin https://github.com/ggml-org/llama.cpp.git
fi
if [[ "$(git -C "$llama_dir" rev-parse HEAD 2>/dev/null || true)" != "$llama_commit" ]]; then
  git -C "$llama_dir" fetch --depth 1 origin "$llama_commit"
  git -C "$llama_dir" checkout --detach FETCH_HEAD
fi

cmake -S "$llama_dir" -B "$llama_dir/build" \
  -DCMAKE_BUILD_TYPE=Release \
  -DGGML_NATIVE=OFF \
  -DGGML_CPU_ARM_ARCH=armv7-a+neon-vfpv4 \
  -DGGML_OPENMP=OFF \
  -DLLAMA_BUILD_TESTS=OFF \
  -DLLAMA_BUILD_EXAMPLES=OFF \
  -DLLAMA_BUILD_SERVER=ON
cmake --build "$llama_dir/build" --target llama-server -j2

mkdir -p "$model_dir"
if [[ ! -f "$model_path" ]]; then
  curl -fL --retry 3 -o "$model_path" "$model_url"
fi
printf '%s  %s\n' "$model_sha256" "$model_path" | sha256sum -c -
printf 'Runtime ready: %s\nModel ready: %s\n' "$llama_dir/build/bin/llama-server" "$model_path"
